["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
ERC721 = [
    "src/token/ERC721/ERC721.cairo",
]

[profile.testnet.protostar.deploy]
network="alpha-goerli"
